#!/usr/bin/with-contenv sh

set -ex

sed -i -e "s/IbLoginId=.*$/IbLoginId=${IB_USERNAME}/" ~/ibc/config.ini
sed -i -e "s/IbPassword=.*$/IbPassword=${IB_PASSWORD}/" ~/ibc/config.ini

exec /opt/ibc/gatewaystart.sh -inline
