#!/usr/bin/with-contenv sh

set -ex

sed -i -e "s/IbLoginId=.*$/IbLoginId=${IB_USERNAME}/" ~/ibc/config.ini
sed -i -e "s/IbPassword=.*$/IbPassword=${IB_PASSWORD}/" ~/ibc/config.ini
sed -i -e "s/TWS_MAJOR_VRSN=.*$/TWS_MAJOR_VRSN=978/" /opt/ibc/gatewaystart.sh

exec /opt/ibc/gatewaystart.sh -inline
