name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build -t ib-gateway .

    - name: Login to registry
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
      env:
        DOCKER_REGISTRY_URL: docker.pkg.github.com
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      if: github.ref == 'refs/heads/master'

    - name: Tag latest
      run: docker tag ib-gateway "docker.pkg.github.com/kid/docker-ib-gateway/ib-gateway:latest"
      if: github.ref == 'refs/heads/master'

    - name: Publish latest
      run: docker push "docker.pkg.github.com/kid/docker-ib-gateway/ib-gateway:latest"
      if: github.ref == 'refs/heads/master'

    - name: Tag release
      run: docker tag ib-gateway "docker.pkg.github.com/kid/docker-ib-gateway/ib-gateway:${REF#heads/tags/}"
      env:
        REF: "${{ github.ref }}"
      if: startsWith(github.ref, 'refs/tags/v')

    - name: Publish release
      run: docker puslish "docker.pkg.github.com/kid/docker-ib-gateway/ib-gateway:${REF#heads/tags/}"
      env:
        REF: "${{ github.ref }}"
      if: startsWith(github.ref, 'refs/tags/v')
