name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make build

    - name: Login to registry
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
      env:
        DOCKER_REGISTRY_URL: docker.pkg.github.com
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')

    - name: docker push
      run: make push
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
